### ISSUE TITLE
Issue with DTEND

### ISSUE THREAD

**Issue by wuebkers** [marcbelletre/acf-rrule#23]
Hey, I have been using this plugin and things have been great, but I am getting this error randomly today and I am hoping you can help resolve this:
`parsestring.js:98 Uncaught (in promise) Error: Unknown RRULE property 'DTEND'`

<img width="444" alt="Screenshot 2023-11-15 at 12 44 43 PM" src="https://github.com/marcbelletre/acf-rrule/assets/9771335/a655d8a6-7942-4bc9-9cff-d4d8ab0a4699">

Everything looks right in my CMS:
<img width="1424" alt="Screenshot 2023-11-15 at 12 45 28 PM" src="https://github.com/marcbelletre/acf-rrule/assets/9771335/7bba63c4-d41c-4b11-b9f4-076827f82611">

**Comment by marcbelletre** [comment]
Hi @wuebkers,

I just answered your support question on Wordpress.org.  

It looks like you're using a Javascript library that does not support the `DTEND` property (I would guess [this one](https://github.com/jkbrzt/rrule/issues/322)?)

This incompatibility with the rrule.js library must have been introduced by [this change](https://github.com/marcbelletre/acf-rrule/commit/910281ebd3d98df57eaa90c62bd412f7a986ecb0#diff-52aa1d1bbe60b2f44b3b49d5473046bd07ac7bdd7aaa4a09d2455c100214817fR789). It looks like this changed has never been tagged until several months later in v1.3.0. I will have to take a deeper look at it to understand why it has been introduced. In the meantime can you try to roll back to v1.2.5?

**Comment by marcbelletre** [comment]
I just removed the `DTEND` attribute from the generated RRULE string which appeared to be completely unnecessary. The RRULE string already contains the `UNTIL` attribute with the exact same value.

In order to ensure backwards compatibility with previous versions of the plugin where `DTEND` attribute was not implemented, the attribute is automatically removed from the string if it exists in database (see [here](https://github.com/marcbelletre/acf-rrule/commit/86fda2d075864e8929f6347e453c38281c7f3f46#diff-52aa1d1bbe60b2f44b3b49d5473046bd07ac7bdd7aaa4a09d2455c100214817fR708)). 

Latest release v1.3.4 has been pushed to packagist.org and Wordpress plugin repository 🚀
